const question = [
    "não é possível só vai até cinco",
    "O envio seria por qual loja? Corpo perfeito?", "Funciona na central ecp max cell 4 gdm?",
    "quanto fica 45 metros? Olá tem número 18 Serve na xre 15/15 ? acompanha cabo extensor?",
    "Tem na cor azul",
    "Boa noite, o cooler funciona através de cabo usb no celular?", "Qual é o consumo em relação a bateria do telefone?",
    "Tem kit sem a milha ?",
    " Acabei de comprar seis canecas e pedi película correio,  porém se estiver na cidade de são. Paulo  retiro amanhã",
    "Disponivel",
    "tem branco?",
    "Manda um link obrigado",
    "Quanto fica pada o CEP: 35.030-070",
    "Esse é aquele óleo MULTIVISCOSO SAE API-SF que vem nos manuais da Honda?",
    "Você emite nota fiscal?",
    "Qual frequência em MHz?",
    "Boa noite! Teria esse modelo com a lente verde no mesmo valor?",
    "Tem branco com cinza?Tem para mesa de 80cm",
    "Entre o cabo e a coletora é de encaixe? Eu digo existe uma separação? Solta?",
    "Qual a duração da bateria?",
    "Boa noite! Qual a data de validade desse remedio?",
    "Tem o produto em estoque?",
    "Gostaria de saber se vocês tem para tamanho de portA padrão.",
    "Boa noite senhores, qual o valor do envio para o cep 21831505. Obrigada",
    "Compensa são boas ? Da pra revender a quantos cada uma.",
    "Posso colocar no mar?",
    "Onde fica a sua loja? posso comprar pelo mercado livre e retirar?",
    "Boa noite. Tem como usar como emissão Bluetooth na TV??. Ou seja...Transmitir o som da TV para um Fone Bluetooth ??!",
    "ola amigo nao tem ele a 1500rms 8ohms pra tocar apenas um falante de 8ohms",
    " O selo de papel resinado é biodegradável?  É possível usar selos de celofane? aguardo, obrigada",
    "Olá. Pq não entregam em Porto Alegre?",
    "Posso colocar no mar?",
    "é primeira linha brasileira ou chinesa? vem conforma foto  funciona o filtro azul",
    "Bom dia, pronta entrega???",
    "A data de fabricação é...?",
    "Boa noite tem dele 220v ? por gentileza obrigado",
    "Vcs teriam esse com Windows 10?",
    "Boa noite tem dele 220v ? por gentileza obrigado",
    "Quanto vc faz 3 para o CEP 72930000.",
    "É original?",
    "Produto original, lacrado e NF? Obg",
    "E.prova.da.agua",
    "Tem verde agua?",
    "Boa noite! Produto ainda em estoque?",
    "Nossa senhora o frete é metade do valor do produto!!! Vocês estão onde na China?",
    "Não está específico o que vem se é os de fora e de dentro ou só os de fora",
    "Meu carro é turbo, rem como instalar esse kit ?",
    "por acaso vc nao tem o outro também em vermelho e cinza?",
    "Tem disponível.?",
    "Tem legenda em Português?",
    "Olá, no caso da biomedicina o pingente vem escrito biomedicina ou química?",
    "Tem algum diferença para esse? https://produto.mercadolivre.com.br/MLB-1391380519-relogio-smartwatch-m3-bracelete-inteligente-black-friday-_JM?variation=48121111313",
    "É a prova da água?",
    "Boa Tarde Posso Ligar Em Um Sistema 5v?",
    "Olá, boa noite!, o aparelho aguenta uma máquina de cortar cabelo de 60 HZ?",
    "Opa! O ktag e o ecm fazem o astra 2011 2.0 8v 140cv Bosch me 7.9.9?",
    "Vocês tem menos de 90% de aprovação positiva, isto é péssimo, tô fora!",
    "Esse é o maior?",
    "bom dia, o controle suporta PC? (Uso Windows 10) É necessário baixar algum driver para o controle poder funcionar ou é só conectar pelo USB e ele é reconhecido normalmente?",
    "Olá,  tirando o peso, eu gostaria de saber qual desses carrinhos é menor quando aberto,  o OHLALA ou o UP ?? Estou em dúvida qual comprar.",
    "Eu n sei meu cep mas se ajudar moro me Santos",
    "ola,bom dia,essa frontal vem com brilho,ou tem ajuste de brilho??? obg/",
    "Suporta i7 3630qm ?",
    "Qual o mês e o ano da validade?",
    "Qual o mês e o ano da validade?",
    "Eu ja paguei o boleto quando chega o.meu relogio",
    "Bom dia , tem esse quadro no tamanho de 1,80 por 90 , e qual o valor ¿",
    "Tem algum colateral?",
    "Fu ciona em qualquer aparelho selular",
    "Da de por selular HDMI para usar motor ou tv com moto G7 play pois ele tem USB tipo c",
    "Vc tem a pronta entrega esse produto.",
    "Ola,",
    "Ainda tem?",
    "Dá pra botar quantas balas?",
    "Qual medida do colchao que vcs recomendam para esse berco ?",
    "Ele é compativel a iphone ?",
    "Faz as 10 frete grátis para 78075-905 que eu compro",
    "Não vem com saco de malha?",
    "Esse relogio e compativel com iphone? Ele recebe mensagem e ligaçao?",
    "Tem em pronta entrega? Quais cores disponíveis?",
    "Amigo comprei uma película com você do Moto One Action e gostaria de saber se é possível trocar pela película do Samsung A10 , por favor !?",
    "Do jeito que veio ela está , a caixa não foi nem aberta , se for possível , agradeço desde já !?",
    "Vem os dois pares de aro",
    "Comprei um celular Moto One Action e acabei trocando por um Samsung A10 e gostaria de te pedir um favor , teria como você trocar pela película do Samsung A10 , do jeito que veio , a caixa está , não foi aberta , se possível fazer a troca , desde já agradeço !?",
    "Olá, 110 v não tem?",
    "Tem assistência técnica em todo Brasil?",
    "Minha bb tem 6  meses daria pra regular?",
    "Bom dia. Qual a data de validade mais próxima dos reagentes? Obrigado!",
    "O console tem Pokemon Ruby, Green ou Platinum?",
    "Ainda tem ela a pronta entrega ?",
    "ainda tem?",
    "Olá amigos, bom dia. Por efeito de comparação, o que torna o Edifier W830bt superior aos seus antecessores W820bt e W800bt..?",
    "Bom dia! O meu moto C e XT1758, esta tela se aplica neste modelo?",
    "este mouse serve p qualquer note com entrada usb e dispensa pilhas",
    "Tem adulto?",
    "Fiz a compra depois perguntei se era de teflom por dentro, perguntei duas vezes e não tive resposta, estou no aguardo, pêlo contrário não tico  com o produto."
]

module.export = question